# Generated by Django 4.2.6 on 2023-10-10 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('parent', models.IntegerField()),
                ('structure_type_code', models.CharField(max_length=255)),
                ('structure_type_name', models.CharField(max_length=255)),
                ('locality_type_code', models.CharField(max_length=255)),
                ('locality_type_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('third_name', models.CharField(max_length=100)),
                ('image', models.URLField()),
                ('student_id_number', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('avg_gpa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_credit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('gender', models.CharField(max_length=20)),
                ('specialty_id', models.CharField(max_length=10)),
                ('group_id', models.CharField(max_length=10)),
                ('education_year_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('citizenship', models.CharField(max_length=100)),
                ('semester_id', models.CharField(max_length=10)),
                ('level', models.CharField(max_length=50)),
                ('education_form', models.CharField(max_length=50)),
                ('education_type', models.CharField(max_length=50)),
                ('payment_form', models.CharField(max_length=50)),
                ('student_type', models.CharField(max_length=50)),
                ('social_category', models.CharField(max_length=50)),
                ('accommodation', models.CharField(max_length=50)),
                ('student_status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hash', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.department')),
            ],
        ),
    ]
